### ISSUE TITLE
Sorting Algorithms

### ISSUE THREAD

**Issue by swaroop-2021** [mohit-dhote/Codify-Platform#38]
I want to add the following sorting algorithms in c++ language,

1) Bubble Sort
2) Selection Sort
3) Insertion Sort
4) Heap Sort
5) Merge Sort
6) Quick Sort

Please Assign me this issue and add the hacktoberfest2023 tags, I am interested to Contribute : )

**Comment by ADrect** [comment]
Please Assign, me this issue.

**Comment by swaroop-2021** [comment]
Please also add the tags hacktoberfest and hacktoberfest-accepted.
