### ISSUE TITLE
Add Boundary Traversal of Matrix.CPP

### ISSUE THREAD

**Issue by Ash0807** [mohit-dhote/Codify-Platform#47]
**Describe the Issue**
We have given a matrix of dimensions n x m. The task is to perform boundary traversal on the matrix in a clockwise manner.

**Sample Input:**
n = 4, m = 4
matrix[ ][ ] = {{1, 2, 3, 4},
{5, 6, 7, 8},
{9, 10, 11, 12},
{13, 14, 15,16}}

**Sample Output:** 1 2 3 4 8 12 16 15 14 13 9 5

**Additional context (optional)**
@mohit-dhote can you please assign this issue to me @Ash0807 under Hacktoberfest label

**Comment by mehadishakil** [comment]
I'd like to work on this. Can you assign it to me with the 'Hacktoberfest' label?
